package Modelo;
// Generated 10/10/2015 03:27:01 PM by Hibernate Tools 4.3.1



/**
 * AlumnoGrupoId generated by hbm2java
 */
public class AlumnoGrupoId  implements java.io.Serializable {


     private int matricula;
     private String grupo;
     private String trimestreLectivo;

    public AlumnoGrupoId() {
    }

    public AlumnoGrupoId(int matricula, String grupo, String trimestreLectivo) {
       this.matricula = matricula;
       this.grupo = grupo;
       this.trimestreLectivo = trimestreLectivo;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public String getTrimestreLectivo() {
        return this.trimestreLectivo;
    }
    
    public void setTrimestreLectivo(String trimestreLectivo) {
        this.trimestreLectivo = trimestreLectivo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlumnoGrupoId) ) return false;
		 AlumnoGrupoId castOther = ( AlumnoGrupoId ) other; 
         
		 return (this.getMatricula()==castOther.getMatricula())
 && ( (this.getGrupo()==castOther.getGrupo()) || ( this.getGrupo()!=null && castOther.getGrupo()!=null && this.getGrupo().equals(castOther.getGrupo()) ) )
 && ( (this.getTrimestreLectivo()==castOther.getTrimestreLectivo()) || ( this.getTrimestreLectivo()!=null && castOther.getTrimestreLectivo()!=null && this.getTrimestreLectivo().equals(castOther.getTrimestreLectivo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMatricula();
         result = 37 * result + ( getGrupo() == null ? 0 : this.getGrupo().hashCode() );
         result = 37 * result + ( getTrimestreLectivo() == null ? 0 : this.getTrimestreLectivo().hashCode() );
         return result;
   }   


}


