package Modelo;
// Generated 10/10/2015 03:27:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int matricula;
     private String nombre;
     private String contrasena;
     private Set alumnoGrupos = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(int matricula) {
        this.matricula = matricula;
    }
    public Alumno(int matricula, String nombre, String contrasena, Set alumnoGrupos) {
       this.matricula = matricula;
       this.nombre = nombre;
       this.contrasena = contrasena;
       this.alumnoGrupos = alumnoGrupos;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set getAlumnoGrupos() {
        return this.alumnoGrupos;
    }
    
    public void setAlumnoGrupos(Set alumnoGrupos) {
        this.alumnoGrupos = alumnoGrupos;
    }




}


