package Modelo;
// Generated 10/10/2015 03:27:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlumnoGrupo generated by hbm2java
 */
public class AlumnoGrupo  implements java.io.Serializable {


     private AlumnoGrupoId id;
     private Alumno alumno;
     private Grupo grupo;
     private Integer claveUea;
     private Set tareaAlumnos = new HashSet(0);
     private Set faseAlumnoTareas = new HashSet(0);

    public AlumnoGrupo() {
    }

	
    public AlumnoGrupo(AlumnoGrupoId id, Alumno alumno, Grupo grupo) {
        this.id = id;
        this.alumno = alumno;
        this.grupo = grupo;
    }
    public AlumnoGrupo(AlumnoGrupoId id, Alumno alumno, Grupo grupo, Integer claveUea, Set tareaAlumnos, Set faseAlumnoTareas) {
       this.id = id;
       this.alumno = alumno;
       this.grupo = grupo;
       this.claveUea = claveUea;
       this.tareaAlumnos = tareaAlumnos;
       this.faseAlumnoTareas = faseAlumnoTareas;
    }
   
    public AlumnoGrupoId getId() {
        return this.id;
    }
    
    public void setId(AlumnoGrupoId id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Integer getClaveUea() {
        return this.claveUea;
    }
    
    public void setClaveUea(Integer claveUea) {
        this.claveUea = claveUea;
    }
    public Set getTareaAlumnos() {
        return this.tareaAlumnos;
    }
    
    public void setTareaAlumnos(Set tareaAlumnos) {
        this.tareaAlumnos = tareaAlumnos;
    }
    public Set getFaseAlumnoTareas() {
        return this.faseAlumnoTareas;
    }
    
    public void setFaseAlumnoTareas(Set faseAlumnoTareas) {
        this.faseAlumnoTareas = faseAlumnoTareas;
    }




}


