package Modelo;
// Generated 10/10/2015 03:27:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FaseAlumnoTarea generated by hbm2java
 */
public class FaseAlumnoTarea  implements java.io.Serializable {


     private FaseAlumnoTareaId id;
     private AlumnoGrupo alumnoGrupo;
     private Fase fase;
     private Tarea tarea;
     private Date tiempoPlaneado;
     private Date tiempoReal;
     private Integer defectosPlaneados;
     private Integer defectosReal;
     private Integer defectosEliminadosReal;
     private Integer defectosEliminadosPlaneados;

    public FaseAlumnoTarea() {
    }

	
    public FaseAlumnoTarea(FaseAlumnoTareaId id, AlumnoGrupo alumnoGrupo, Fase fase, Tarea tarea) {
        this.id = id;
        this.alumnoGrupo = alumnoGrupo;
        this.fase = fase;
        this.tarea = tarea;
    }
    public FaseAlumnoTarea(FaseAlumnoTareaId id, AlumnoGrupo alumnoGrupo, Fase fase, Tarea tarea, Date tiempoPlaneado, Date tiempoReal, Integer defectosPlaneados, Integer defectosReal, Integer defectosEliminadosReal, Integer defectosEliminadosPlaneados) {
       this.id = id;
       this.alumnoGrupo = alumnoGrupo;
       this.fase = fase;
       this.tarea = tarea;
       this.tiempoPlaneado = tiempoPlaneado;
       this.tiempoReal = tiempoReal;
       this.defectosPlaneados = defectosPlaneados;
       this.defectosReal = defectosReal;
       this.defectosEliminadosReal = defectosEliminadosReal;
       this.defectosEliminadosPlaneados = defectosEliminadosPlaneados;
    }
   
    public FaseAlumnoTareaId getId() {
        return this.id;
    }
    
    public void setId(FaseAlumnoTareaId id) {
        this.id = id;
    }
    public AlumnoGrupo getAlumnoGrupo() {
        return this.alumnoGrupo;
    }
    
    public void setAlumnoGrupo(AlumnoGrupo alumnoGrupo) {
        this.alumnoGrupo = alumnoGrupo;
    }
    public Fase getFase() {
        return this.fase;
    }
    
    public void setFase(Fase fase) {
        this.fase = fase;
    }
    public Tarea getTarea() {
        return this.tarea;
    }
    
    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
    }
    public Date getTiempoPlaneado() {
        return this.tiempoPlaneado;
    }
    
    public void setTiempoPlaneado(Date tiempoPlaneado) {
        this.tiempoPlaneado = tiempoPlaneado;
    }
    public Date getTiempoReal() {
        return this.tiempoReal;
    }
    
    public void setTiempoReal(Date tiempoReal) {
        this.tiempoReal = tiempoReal;
    }
    public Integer getDefectosPlaneados() {
        return this.defectosPlaneados;
    }
    
    public void setDefectosPlaneados(Integer defectosPlaneados) {
        this.defectosPlaneados = defectosPlaneados;
    }
    public Integer getDefectosReal() {
        return this.defectosReal;
    }
    
    public void setDefectosReal(Integer defectosReal) {
        this.defectosReal = defectosReal;
    }
    public Integer getDefectosEliminadosReal() {
        return this.defectosEliminadosReal;
    }
    
    public void setDefectosEliminadosReal(Integer defectosEliminadosReal) {
        this.defectosEliminadosReal = defectosEliminadosReal;
    }
    public Integer getDefectosEliminadosPlaneados() {
        return this.defectosEliminadosPlaneados;
    }
    
    public void setDefectosEliminadosPlaneados(Integer defectosEliminadosPlaneados) {
        this.defectosEliminadosPlaneados = defectosEliminadosPlaneados;
    }




}


