package Modelo;
// Generated 10/10/2015 03:27:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private GrupoId id;
     private Profesor profesor;
     private Integer cupo;
     private Integer numeroInscritos;
     private Set alumnoGrupos = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(GrupoId id) {
        this.id = id;
    }
    public Grupo(GrupoId id, Profesor profesor, Integer cupo, Integer numeroInscritos, Set alumnoGrupos) {
       this.id = id;
       this.profesor = profesor;
       this.cupo = cupo;
       this.numeroInscritos = numeroInscritos;
       this.alumnoGrupos = alumnoGrupos;
    }
   
    public GrupoId getId() {
        return this.id;
    }
    
    public void setId(GrupoId id) {
        this.id = id;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Integer getCupo() {
        return this.cupo;
    }
    
    public void setCupo(Integer cupo) {
        this.cupo = cupo;
    }
    public Integer getNumeroInscritos() {
        return this.numeroInscritos;
    }
    
    public void setNumeroInscritos(Integer numeroInscritos) {
        this.numeroInscritos = numeroInscritos;
    }
    public Set getAlumnoGrupos() {
        return this.alumnoGrupos;
    }
    
    public void setAlumnoGrupos(Set alumnoGrupos) {
        this.alumnoGrupos = alumnoGrupos;
    }




}


