package Modelo;
// Generated 10/10/2015 03:27:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarea generated by hbm2java
 */
public class Tarea  implements java.io.Serializable {


     private int idTarea;
     private String nombreTarea;
     private Set tareaAlumnos = new HashSet(0);
     private Set faseAlumnoTareas = new HashSet(0);

    public Tarea() {
    }

	
    public Tarea(int idTarea, String nombreTarea) {
        this.idTarea = idTarea;
        this.nombreTarea = nombreTarea;
    }
    public Tarea(int idTarea, String nombreTarea, Set tareaAlumnos, Set faseAlumnoTareas) {
       this.idTarea = idTarea;
       this.nombreTarea = nombreTarea;
       this.tareaAlumnos = tareaAlumnos;
       this.faseAlumnoTareas = faseAlumnoTareas;
    }
   
    public int getIdTarea() {
        return this.idTarea;
    }
    
    public void setIdTarea(int idTarea) {
        this.idTarea = idTarea;
    }
    public String getNombreTarea() {
        return this.nombreTarea;
    }
    
    public void setNombreTarea(String nombreTarea) {
        this.nombreTarea = nombreTarea;
    }
    public Set getTareaAlumnos() {
        return this.tareaAlumnos;
    }
    
    public void setTareaAlumnos(Set tareaAlumnos) {
        this.tareaAlumnos = tareaAlumnos;
    }
    public Set getFaseAlumnoTareas() {
        return this.faseAlumnoTareas;
    }
    
    public void setFaseAlumnoTareas(Set faseAlumnoTareas) {
        this.faseAlumnoTareas = faseAlumnoTareas;
    }




}


